//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrdDetail
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductsID { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PurchasePrice { get; set; }
        public Nullable<int> StockID { get; set; }
        public Nullable<int> QtyProm { get; set; }
        public string QtyPromAmt { get; set; }
        public string AmtProm { get; set; }
        public string TaxAmt { get; set; }
        public string Amount { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
