//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public County()
        {
            this.GovOfficeRegions = new HashSet<GovOfficeRegion>();
            this.Towns = new HashSet<Town>();
        }
    
        public int CountyID { get; set; }
        public int CountryID { get; set; }
        public string CountyName { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<GovOfficeRegion> GovOfficeRegions { get; set; }
        public virtual ICollection<Town> Towns { get; set; }
    }
}
