//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int DepartmentID { get; set; }
        public Nullable<int> DirectorateID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentShortDescription { get; set; }
        public string DepartmentAddressLine1 { get; set; }
        public string DepartmentAddressLine2 { get; set; }
        public string DepartmentAddressLine3 { get; set; }
        public string DepartmentWebAddress { get; set; }
        public string DepartmentPostcode { get; set; }
        public string DepartmentTownVillageCity { get; set; }
        public string DepartmentCounty { get; set; }
        public string DepartmentNationCountry { get; set; }
        public string DepartmentFullDescription { get; set; }
        public string DepartmentPhoneNumber { get; set; }
        public string DepartmentFax { get; set; }
        public string DepartmentEmail { get; set; }
        public Nullable<bool> DepartmentStatus { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Directorate Directorate { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
