//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directorate
    {
        public Directorate()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public int DirectorateID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> OrgID { get; set; }
        public string DirectorateName { get; set; }
        public string DirectoratePhoneNumber { get; set; }
        public string DirectorateFax { get; set; }
        public string DirectorateEmail { get; set; }
        public string DirectorateWebAddress { get; set; }
        public Nullable<int> DirectorateCharityNumber { get; set; }
        public Nullable<int> DirectorateCompanyNumber { get; set; }
        public string DirectorateAddressLine1 { get; set; }
        public string DirectorateAddressLine2 { get; set; }
        public string DirectorateAddressLine3 { get; set; }
        public string DirectorateCountry { get; set; }
        public string DirectorateShortDescription { get; set; }
        public string DirectorateFullDescription { get; set; }
        public string DirectorateNationCountry { get; set; }
        public string DirectorateTownVillageCity { get; set; }
        public string DirectoratePostcode { get; set; }
        public string DirectorateStatus { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
