//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovOfficeRegion
    {
        public int GovOfficeRegionID { get; set; }
        public Nullable<int> CountyID { get; set; }
        public string GovOfficeRegionName { get; set; }
        public Nullable<bool> GovOfficeRegionIsActive { get; set; }
        public string GovOfficeRegionShortDescription { get; set; }
    
        public virtual County County { get; set; }
    }
}
