//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Premises = new HashSet<Premise>();
            this.Organisations = new HashSet<Organisation>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceActive { get; set; }
        public string ShortDescription { get; set; }
        public string DeptCode { get; set; }
        public string ClientDescription { get; set; }
        public string DeliveryDescription { get; set; }
        public string Attendance { get; set; }
        public Nullable<System.DateTime> StartExpected { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Extendable { get; set; }
        public Nullable<int> ExtendableYears { get; set; }
        public Nullable<int> ExtendableMonths { get; set; }
        public string ContractCode { get; set; }
        public string ContractValue { get; set; }
        public Nullable<bool> StagedPayment { get; set; }
        public string ReferalProcessMethod { get; set; }
        public Nullable<bool> TimeLimited { get; set; }
        public Nullable<int> TimeLimitedYears { get; set; }
        public Nullable<int> TimeLimitedMonths { get; set; }
    
        public virtual ICollection<Premise> Premises { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
    }
}
