//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustRegion
    {
        public TrustRegion()
        {
            this.TrustDistricts = new HashSet<TrustDistrict>();
        }
    
        public int TrustRegionID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string TrustRegionName { get; set; }
        public Nullable<bool> TrustRegionIsActive { get; set; }
        public string TrustRegionShortDescription { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<TrustDistrict> TrustDistricts { get; set; }
    }
}
