//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Payments = new HashSet<Payment>();
            this.SalesOrders = new HashSet<SalesOrder>();
        }
        [Key]
        [Required]
        [Display(Name = "Mã")]
        [StringLength(6, ErrorMessage = "Định dạng [KH0001]")]
        public string CustID { get; set; }
        [Required]
        [Display(Name = "Tên")]
        [StringLength(50, ErrorMessage = "Tên không quá 50 kí tự")]
        public string CustName { get; set; }
        [Display(Name = "Địa chỉ")]
        [StringLength(50, ErrorMessage = "Tên không quá 50 kí tự")]
        public string Address { get; set; }
        [Display(Name = "Điện thoại")]
        [StringLength(11, ErrorMessage = "Tên không quá 11 kí tự")]
        public string Phone { get; set; }
        [Display(Name = "Fax")]
        [StringLength(11, ErrorMessage = "Tên không quá 11 kí tự")]
        public string Fax { get; set; }

        public string Email { get; set; }

        public int Overdue { get; set; }
        [Display(Name = "Nợ")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> Amount { get; set; }
        [Display(Name = "Nợ quá hạn")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> OverdueAmt { get; set; }
        [Display(Name = "Nợ đến hạn")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> DueAmt { get; set; }
        [Required]
        [Display(Name = "Trạng thái")]
        [StringLength(2, ErrorMessage = "2 kí tự")]
        public string Status { get; set; }
        [Display(Name = "Mô tả")]
        [StringLength(50, ErrorMessage = "Tên không quá 200 kí tự")]
        public string Description { get; set; }

        public string SalesManID { get; set; }
    
        public virtual SalesMan SalesMan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
