//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderType { get; set; }
        public string SalesPersonID { get; set; }
        public Nullable<System.DateTime> OverdueDate { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public Nullable<double> PromAmt { get; set; }
        public Nullable<double> ComAmt { get; set; }
        public Nullable<double> TaxAmt { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
    
        public virtual SalesMan SalesMan { get; set; }
    }
}
