//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnGoodsDetail
    {
        public int ReturnGoodsDetailID { get; set; }
        public int ReturnGoodsID { get; set; }
        public string ProductsID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Deals { get; set; }
        public string ReasonReturn { get; set; }
        public string Description { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
