//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlsOrderDetail
    {
        public int ID { get; set; }
        [Display(Name = "Order No")]
        [Required]
        public string OrderNo { get; set; }
        [Required]
        [Display(Name = "Inventory ID")]
        public string InvtID { get; set; }
        public Nullable<int> Qty { get; set; }
        [Display(Name = "Sales Price")]
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        [Display(Name = "Tax Amount")]
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
