//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransfer
    {
        public string StockTransferID { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> FromStockID { get; set; }
        public Nullable<int> ToStockID { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public string Description { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Stock Stock1 { get; set; }
    }
}
