//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractParticipationType
    {
        public ContractParticipationType()
        {
            this.Services = new HashSet<Service>();
        }
    
        public int ContractParticipationTypeId { get; set; }
        public string ContractParticipationTypeName { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
    }
}
