//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationType
    {
        public LocationType()
        {
            this.Premise_LocationType = new HashSet<Premise_LocationType>();
        }
    
        public int LocationTypeId { get; set; }
        public string LocationTypeName { get; set; }
    
        public virtual ICollection<Premise_LocationType> Premise_LocationType { get; set; }
    }
}
