//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Directorates = new HashSet<Directorate>();
            this.Organization_Programme = new HashSet<Organization_Programme>();
            this.Organization_RefDataDetail = new HashSet<Organization_RefDataDetail>();
            this.Premises = new HashSet<Premise>();
            this.Service_Organization_OrganizationRoleType = new HashSet<Service_Organization_OrganizationRoleType>();
            this.SupportingMaterials = new HashSet<SupportingMaterial>();
        }
    
        public int OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationShortDescription { get; set; }
        public int LeadContactId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Postcode { get; set; }
        public string CityTown { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> IsPreferredOrganization { get; set; }
        public Nullable<bool> IsExpressionOfInterest { get; set; }
        public string TypeOfBusiness { get; set; }
        public string SICCode { get; set; }
        public string OrganizationFullDescription { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public string CharityNumber { get; set; }
        public string CompanyNumber { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Country Country { get; set; }
        public virtual County County { get; set; }
        public virtual ICollection<Directorate> Directorates { get; set; }
        public virtual ICollection<Organization_Programme> Organization_Programme { get; set; }
        public virtual ICollection<Organization_RefDataDetail> Organization_RefDataDetail { get; set; }
        public virtual ICollection<Premise> Premises { get; set; }
        public virtual ICollection<Service_Organization_OrganizationRoleType> Service_Organization_OrganizationRoleType { get; set; }
        public virtual ICollection<SupportingMaterial> SupportingMaterials { get; set; }
    }
}
