//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationRoleType
    {
        public OrganizationRoleType()
        {
            this.Service_Organization_OrganizationRoleType = new HashSet<Service_Organization_OrganizationRoleType>();
        }
    
        public int OrganizationRoleTypeId { get; set; }
        public string OrganizationRoleTypeName { get; set; }
    
        public virtual ICollection<Service_Organization_OrganizationRoleType> Service_Organization_OrganizationRoleType { get; set; }
    }
}
