//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premise
    {
        public Premise()
        {
            this.Premise_LocationType = new HashSet<Premise_LocationType>();
            this.Service_Premise = new HashSet<Service_Premise>();
        }
    
        public int PremiseId { get; set; }
        public string LocationName { get; set; }
        public string KnownAs { get; set; }
        public Nullable<int> LocationOrganizationId { get; set; }
        public int LocationStatusId { get; set; }
        public Nullable<System.DateTime> LocationStatusDate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Postcode { get; set; }
        public string CityTown { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> IsPrimaryLocation { get; set; }
        public Nullable<bool> IsLocationManaged { get; set; }
        public Nullable<bool> HasSTNetworkConnectivity { get; set; }
        public string LocationDescription { get; set; }
        public string PhoneNumber { get; set; }
        public string GeneralFaxNumber { get; set; }
        public string MinicommNumber { get; set; }
        public Nullable<bool> IsNewShop { get; set; }
        public Nullable<System.DateTime> ShopFlagDate { get; set; }
        public Nullable<bool> IsSpecialistShop { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual County County { get; set; }
        public virtual LocationStatu LocationStatu { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Premise_LocationType> Premise_LocationType { get; set; }
        public virtual ICollection<Service_Premise> Service_Premise { get; set; }
    }
}
