//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefData
    {
        public RefData()
        {
            this.RefDataDetails = new HashSet<RefDataDetail>();
        }
    
        public int RefDataId { get; set; }
        public string RefDataName { get; set; }
        public string RefDataValue { get; set; }
    
        public virtual ICollection<RefDataDetail> RefDataDetails { get; set; }
    }
}
