//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Service_Organization_OrganizationRoleType = new HashSet<Service_Organization_OrganizationRoleType>();
            this.Service_Premise = new HashSet<Service_Premise>();
            this.Service_RefDataDetail = new HashSet<Service_RefDataDetail>();
            this.ServiceFundings = new HashSet<ServiceFunding>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string ServiceShortDescription { get; set; }
        public int ServiceSubTypeId { get; set; }
        public int LeadContactId { get; set; }
        public string ClientDescription { get; set; }
        public string ServiceAttendance { get; set; }
        public Nullable<System.DateTime> ServiceStartExpected { get; set; }
        public Nullable<System.DateTime> ServiceStartDate { get; set; }
        public Nullable<System.DateTime> ServiceEndDate { get; set; }
        public Nullable<bool> ServiceExtendable { get; set; }
        public Nullable<int> ServiceExtendableMonth { get; set; }
        public Nullable<int> ServiceExtendableYear { get; set; }
        public string ServiceFullDescription { get; set; }
        public string DepartmentCode { get; set; }
        public int ServiceTypeId { get; set; }
        public string ServiceDescriptionDelivery { get; set; }
        public string ServiceContractCode { get; set; }
        public string ServiceContractValue { get; set; }
        public Nullable<bool> IsContractStagedPayment { get; set; }
        public Nullable<int> ReferralMethodId { get; set; }
        public Nullable<bool> IsTimeLimited { get; set; }
        public Nullable<int> LimitedYears { get; set; }
        public Nullable<int> LimitedMonths { get; set; }
        public Nullable<int> ProgrammeId { get; set; }
        public Nullable<int> ContractParticipationTypeId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ContractParticipationType ContractParticipationType { get; set; }
        public virtual Programme Programme { get; set; }
        public virtual ReferralMethod ReferralMethod { get; set; }
        public virtual ICollection<Service_Organization_OrganizationRoleType> Service_Organization_OrganizationRoleType { get; set; }
        public virtual ICollection<Service_Premise> Service_Premise { get; set; }
        public virtual ICollection<Service_RefDataDetail> Service_RefDataDetail { get; set; }
        public virtual ServiceSubType ServiceSubType { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual ICollection<ServiceFunding> ServiceFundings { get; set; }
    }
}
