//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public string TeamShortDescription { get; set; }
        public Nullable<int> LeadContactId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Postcode { get; set; }
        public string TownVillageCity { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string TypeOfBusiness { get; set; }
        public string SICCode { get; set; }
        public string TeamFullDescription { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public bool IsActive { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Country Country { get; set; }
        public virtual County County { get; set; }
    }
}
