//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustRegion
    {
        public TrustRegion()
        {
            this.TrustDistricts = new HashSet<TrustDistrict>();
        }
    
        public int TrustRegionId { get; set; }
        public int CountryId { get; set; }
        public string TrustRegionName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<TrustDistrict> TrustDistricts { get; set; }
    }
}
