//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovOfficeRegion
    {
        public GovOfficeRegion()
        {
            this.GovOfficeRegion_County = new HashSet<GovOfficeRegion_County>();
        }
    
        public int GovOfficeRegionId { get; set; }
        public string GovOfficeRegionName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<GovOfficeRegion_County> GovOfficeRegion_County { get; set; }
    }
}
