//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Premise
    {
        public int Service_PremiseId { get; set; }
        public int ServiceId { get; set; }
        public int PremiseId { get; set; }
    
        public virtual Premise Premise { get; set; }
        public virtual Service Service { get; set; }
    }
}
