//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class GovOfficeRegion_County
    {
        public int GovOfficeRegion_CountyId { get; set; }
        public int GovOfficeRegionId { get; set; }
        public int CountyId { get; set; }
    
        public virtual County County { get; set; }
        public virtual GovOfficeRegion GovOfficeRegion { get; set; }
    }
}
