//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Organization_OrganizationRoleType
    {
        public int Service_Organization_OrganizationRoleTypeId { get; set; }
        public int ServiceId { get; set; }
        public int OrganizationId { get; set; }
        public int OrganizationRoleTypeId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual OrganizationRoleType OrganizationRoleType { get; set; }
        public virtual Service Service { get; set; }
    }
}
