// <auto-generated />
namespace CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class remove_att_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_att_date));
        
        string IMigrationMetadata.Id
        {
            get { return "201508051151094_remove_att_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
