//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportingMaterial
    {
        public int SupportingMaterialID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> OrgID { get; set; }
        public string URL { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string SupportingMaterialDescription { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
    }
}
