//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerType
    {
        public CustomerType()
        {
            this.RFONumbers = new HashSet<RFONumber>();
        }
    
        public int CustomerTypeId { get; set; }
        public string CustomerType1 { get; set; }
    
        public virtual ICollection<RFONumber> RFONumbers { get; set; }
    }
}
