//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundingMethod
    {
        public FundingMethod()
        {
            this.Agreements = new HashSet<Agreement>();
        }
    
        public int FundingMethodId { get; set; }
        public string FundingMethodName { get; set; }
        public string FundingType { get; set; }
        public string ContractTemplateLocation { get; set; }
        public string SignedContractDefault { get; set; }
        public string Status { get; set; }
        public string AMISDeptCode { get; set; }
        public string AMISReasonCode { get; set; }
    
        public virtual ICollection<Agreement> Agreements { get; set; }
    }
}
