//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Payment
    {
        [Display(Name = "Mã phiếu thanh toán")]
        [Required(ErrorMessage = "Phải nhập trường này")]
        public int PaymentID { get; set; }

        [Display(Name = "Số tiền phải trả")]
        [Required(ErrorMessage = "Phải nhập trường này")]
        public string PaymentNo { get; set; }

        [Display(Name = "Ngày thanh toán")]
        public Nullable<System.DateTime> PaymentDate { get; set; }

        [Display(Name = "Số tiền thanh toán")]
        public Nullable<decimal> PaymentAmt { get; set; }

        [Required(ErrorMessage = "Phải chọn dữ liệu cho trường này")]
        public string CustID { get; set; }

        [Required(ErrorMessage = "Phải chọn dữ liệu cho trường này")]
        public string SalesPersonID { get; set; }

        [Display(Name = "Ghi chú")]
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesMan SalesMan { get; set; }
    }
}
