//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Contact1 = new HashSet<Contact>();
            this.Departments = new HashSet<Department>();
            this.Directorates = new HashSet<Directorate>();
            this.Organisations = new HashSet<Organisation>();
            this.Programmes = new HashSet<Programme>();
            this.Teams = new HashSet<Team>();
        }
    
        public int ContactID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string FirstName { get; set; }
        public string SurnName { get; set; }
        public string KnowAs { get; set; }
        public string ContactType { get; set; }
        public string BestContactMethod { get; set; }
        public string MobilePhone { get; set; }
        public string OfficePhone { get; set; }
        public string STHomePhone { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<bool> ContactIsActive { get; set; }
        public string Workbase { get; set; }
        public string JobRole { get; set; }
    
        public virtual ICollection<Contact> Contact1 { get; set; }
        public virtual Contact Contact2 { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Directorate> Directorates { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
        public virtual ICollection<Programme> Programmes { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
