//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ReturnGood
    {
        [Display(Name = "Mã trả hàng")]
        [Required(ErrorMessage = "Phải chọn dữ liệu cho trường này")]
        public int ReturnGoodsID { get; set; }

        [Display(Name = "Mã thủ kho")]
        [Required(ErrorMessage = "Phải chọn dữ liệu cho trường này")]
        public string IDUser { get; set; }

        [Display(Name = "Mã Nhân viên bán hàng")]
        [Required(ErrorMessage = "Phải chọn dữ liệu cho trường này")]
        public string SaleManID { get; set; }

        [Display(Name = "Ngày trả hàng")]
        [Required(ErrorMessage = "Phải chọn dữ liệu cho trường này")]
        public Nullable<System.DateTime> DaReturnGoods { get; set; }

        [Display(Name = "Tổng tiền")]
        [Required(ErrorMessage = "Phải nhập dữ liệu cho trường này")]
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual SalesMan SalesMan { get; set; }
        public virtual User User { get; set; }
    }
}
