//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public string SoHD { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public string NguoiLapHD { get; set; }
        public string HinhThucThanhToan { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
