//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSCVT
    {
        public int NSYSCONFIGVALID { get; set; }
        public string XCONFIGVALUE { get; set; }
        public Nullable<int> NORDER { get; set; }
        public Nullable<int> NSYSTEMCONFGID { get; set; }
    
        public virtual SYSCFT SYSCFT { get; set; }
    }
}
