//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.RFONumbers = new HashSet<RFONumber>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string Sector { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Emailaddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string AMISCode { get; set; }
        public string BusinessArea { get; set; }
    
        public virtual ICollection<RFONumber> RFONumbers { get; set; }
    }
}
