//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSCFT
    {
        public SYSCFT()
        {
            this.SYSCVTs = new HashSet<SYSCVT>();
        }
    
        public int NSYSTEMCONFGID { get; set; }
        public string XSYSCONFIGNAME { get; set; }
    
        public virtual ICollection<SYSCVT> SYSCVTs { get; set; }
    }
}
