//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.RFOUsers = new HashSet<RFOUser>();
        }
    
        public int UserTypeId { get; set; }
        public string UserType1 { get; set; }
    
        public virtual ICollection<RFOUser> RFOUsers { get; set; }
    }
}
