//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustDistrict
    {
        public int TrustDistrictId { get; set; }
        public string TrustDistrictName { get; set; }
        public string Description { get; set; }
        public int TrustRegionId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TrustRegion TrustRegion { get; set; }
    }
}
