//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS_G06.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSSEntities : DbContext
    {
        public CSSEntities()
            : base("name=CSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AgendaPayment> AgendaPayments { get; set; }
        public virtual DbSet<Agreement> Agreements { get; set; }
        public virtual DbSet<AgreementStatu> AgreementStatus { get; set; }
        public virtual DbSet<Banding> Bandings { get; set; }
        public virtual DbSet<BudgetCode> BudgetCodes { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CommentType> CommentTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyAddress> CompanyAddresses { get; set; }
        public virtual DbSet<ContactAddress> ContactAddresses { get; set; }
        public virtual DbSet<CostCentre> CostCentres { get; set; }
        public virtual DbSet<CreditNoteText> CreditNoteTexts { get; set; }
        public virtual DbSet<CustomerType> CustomerTypes { get; set; }
        public virtual DbSet<FundingMethod> FundingMethods { get; set; }
        public virtual DbSet<PostCode> PostCodes { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RFONumber> RFONumbers { get; set; }
        public virtual DbSet<RFOUser> RFOUsers { get; set; }
        public virtual DbSet<SystemConfig> SystemConfigs { get; set; }
        public virtual DbSet<SystemConfigValue> SystemConfigValues { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Volume> Volumes { get; set; }
    }
}
