//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS_G06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfigValue
    {
        public int SystemConfigValueId { get; set; }
        public int SystemConfigId { get; set; }
        public string ConfigValue { get; set; }
        public int Order { get; set; }
    
        public virtual SystemConfig SystemConfig { get; set; }
    }
}
