//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programme
    {
        public Programme()
        {
            this.Organization_Programme = new HashSet<Organization_Programme>();
            this.Services = new HashSet<Service>();
        }
    
        public int ProgrammeId { get; set; }
        public string ProgrammeName { get; set; }
        public string ProgrammeDescription { get; set; }
        public Nullable<int> ContactId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Organization_Programme> Organization_Programme { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
