//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.Directorates = new HashSet<Directorate>();
            this.SupportingMaterials = new HashSet<SupportingMaterial>();
            this.Programmes = new HashSet<Programme>();
            this.Services = new HashSet<Service>();
        }
    
        public int OrgID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string OrgName { get; set; }
        public Nullable<bool> OrganisationPreferred { get; set; }
        public Nullable<bool> OrganisationExpressionOfInterest { get; set; }
        public string OrganisationAddressLine1 { get; set; }
        public string OrganisationAddressLine2 { get; set; }
        public string OrganisationAddressLine3 { get; set; }
        public Nullable<decimal> OrganisationPremiseNumber { get; set; }
        public Nullable<decimal> OrganisationFax { get; set; }
        public string OrganisationEmail { get; set; }
        public string OrganisationWebAddress { get; set; }
        public Nullable<decimal> OrganisationCharityNumber { get; set; }
        public Nullable<decimal> OrganisationCompanyNumber { get; set; }
        public string OrganisationPostode { get; set; }
        public string OrganisationCityTown { get; set; }
        public string OrganisationNationCountry { get; set; }
        public string OrganisationCounty { get; set; }
        public string OrganisationShortDescription { get; set; }
        public string OrganisationFullDescription { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Directorate> Directorates { get; set; }
        public virtual ICollection<SupportingMaterial> SupportingMaterials { get; set; }
        public virtual ICollection<Programme> Programmes { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
