//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportingMaterialType
    {
        public SupportingMaterialType()
        {
            this.SupportingMaterials = new HashSet<SupportingMaterial>();
        }
    
        public int SupportingMaterialTypeId { get; set; }
        public string SupportingMaterialTypeName { get; set; }
    
        public virtual ICollection<SupportingMaterial> SupportingMaterials { get; set; }
    }
}
