//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premise
    {
        public int PremiseID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string PremiseName { get; set; }
        public string PrimaryLocation { get; set; }
        public string PremisePhoneNumber { get; set; }
        public string PremiseAddress { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
