//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSSEntities1 : DbContext
    {
        public CSSEntities1()
            : base("name=CSSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agreement> Agreements { get; set; }
        public DbSet<AgreementStatu> AgreementStatus { get; set; }
        public DbSet<Banding> Bandings { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<CommentType> CommentTypes { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<ContactAddress> ContactAddresses { get; set; }
        public DbSet<CreditNoteText> CreditNoteTexts { get; set; }
        public DbSet<CustomerType> CustomerTypes { get; set; }
        public DbSet<FundingMethod> FundingMethods { get; set; }
        public DbSet<RFONumber> RFONumbers { get; set; }
        public DbSet<RFOUser> RFOUsers { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<Volume> Volumes { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<VolumeDiscountType> VolumeDiscountTypes { get; set; }
    }
}
