//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFONumber
    {
        public RFONumber()
        {
            this.Agreements = new HashSet<Agreement>();
        }
    
        public int RFONumber1 { get; set; }
        public string RFOName { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string PostCode { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual ICollection<Agreement> Agreements { get; set; }
    }
}
