//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programme
    {
        public Programme()
        {
            this.Organisations = new HashSet<Organisation>();
        }
    
        public int ProgrammeID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string ProgrammeName { get; set; }
        public string ProgrammeDescription { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
    }
}
