//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportingMaterial
    {
        public int SupportingMaterialId { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public int SupportingMaterialTypeId { get; set; }
        public int UserAddedId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsActive { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual SupportingMaterialType SupportingMaterialType { get; set; }
    }
}
