//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolumeDiscountType
    {
        public VolumeDiscountType()
        {
            this.Agreements = new HashSet<Agreement>();
        }
    
        public int VolumeDiscountTypeId { get; set; }
        public string VolumeDiscountTypeName { get; set; }
    
        public virtual ICollection<Agreement> Agreements { get; set; }
    }
}
