//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesDirectory.Models.DatabaseMapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefDataDetail
    {
        public RefDataDetail()
        {
            this.Organization_RefDataDetail = new HashSet<Organization_RefDataDetail>();
            this.Service_RefDataDetail = new HashSet<Service_RefDataDetail>();
        }
    
        public int RefDataDetailId { get; set; }
        public string RefDataDetailValue { get; set; }
        public int RefDataId { get; set; }
    
        public virtual ICollection<Organization_RefDataDetail> Organization_RefDataDetail { get; set; }
        public virtual RefData RefData { get; set; }
        public virtual ICollection<Service_RefDataDetail> Service_RefDataDetail { get; set; }
    }
}
